.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PAGEMON 8 "January 31, 2016"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.nr SS ((\n[.l] - \n[.i]) / 1n - 24)
.SH NAME
pagemon \- a tool to monitor memory pages.
.br

.SH SYNOPSIS
.B pagemon
.RI [options] 
.br

.SH DESCRIPTION
pagemon is a program that allows one to interactively monitor the memory
pages of a process.

.SH OPTIONS
pagemon options are as follow:
.TP
.B \-a
enable automatic zoom mode, this will change the zoom level to show
the entire page map in the window, up to a maximum zoom level of 999.
.TP
.B \-d delay
delay in microseconds between data refreshes, the default is 10,000
microseconds (1/100th of a second).
.TP
.B \-h
show help.
.TP
.B \-p
specify the process id (PID) or name of the process to monitor. If a name
is given, then pagemon will monitor the first process that matches the name.
.TP
.B \-r
read pages into memory. This will force all pages in the process to be read
into physical memory.
.TP
.B \-t ticks
specify ticks between dirty page checks. The default is 60 ticks; the larger
the value the longer time between dirty page checks.
.TP
.B \-v
enable VM information view. This is equivalent to pressing the 'v' or 'V' key
when running pagemon.
.TP
.B \-z zoom
specify the default zoom level on page view, the default is 1 (that is 1\-to\-1
view of pages).  Higher values increase the zoom level so more pages are
represented in the map view.
.SH KEYS
.TS
expand;
lB lBw(\n[SS]n)
l l.
Key	Explanation
Home	Move cursor to start of page map or start of page
End	Move cursor to end of page map or end of page
Cursor Up	Move cursor up
Cursor Down	Move cursor down
Cursor Left	Move cursor left
Cursor Right	Move cursor right
Page Up	Move cursor 1/2 page up
Page Down	Move cursor 1/2 page down
Esc, q, Q	Quit
Enter	Toggle page map / memory map view
Tab	Toggle detailed view of page
a, A	Toggle automatic zoom mode
v, V	Toggle Virtual Memory statistics of process
p, P	Toggle page statistics
?, h	Toggle help
c, C	Close all the pop up windows
r, R	Force all pages in process to be read into memory
t	Increase ticks between Dirty Page updates
T	Decrease ticks between Dirty Page updates
+, z	Zoom in (only in page map view)
-, Z	Zoom out (only in page map view)
[	Zoom scale to 1, turn off automatic zoom mode
]	Zoom scale to 999, turn off automatic zoom mode
.TE
.SH EXAMPLES
.LP
Monitor the thunderbird process:
.RS 8
sudo pagemon -p thunderbird
.RE
.LP
Monitor process 1 (init), zoom scale of 4:
.RS 8
sudo pagemon -p 1 -z 4
.RE
.SH AUTHOR
pagemon was written by Colin King <colin.king@canonical.com> with contributions
from Dr. David Alan Gilbert.
.PP
This manual page was written by Colin King <colin.king@canonical.com>,
for the Ubuntu project (but may be used by others).
.SH COPYRIGHT
Copyright \(co 2016 Canonical Ltd.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
